### ISSUE TITLE
dependency issue with plug_cowboy 2.7 and gun 1.3

### ISSUE THREAD

**Issue by niranjanaryan** [msantos/runlet#1]
we are exploring for Liveview app with runlet, we receiving dependency errors

Resolving Hex dependencies...
Resolution completed in 0.83s
    Because gun >= 1.2.0 and < 1.3.3 depends on cowlib ~> 2.6.0 and gun >= 1.3.3 and < 2.0.0-rc.1 depends on cowlib ~> 2.7.0, gun >= 1.2.0 and < 2.0.0-rc.1 requires cowlib ~> 2.6.0 or ~> 2.7.0.
(1) So, because every version of runlet depends on gun ~> 1.3, runlet requires cowlib ~> 2.6.0 or ~> 2.7.0.

    Because cowboy >= 2.7.0 and < 2.8.0 depends on cowlib ~> 2.8.0 and cowboy >= 2.8.0 and < 2.9.0 depends on cowlib ~> 2.9.1, cowboy >= 2.7.0 and < 2.9.0 requires cowlib ~> 2.8.0 or ~> 2.9.1.
    And because cowboy >= 2.9.0 and < 2.10.0 depends on cowlib 2.11.0, cowboy >= 2.7.0 and < 2.10.0 requires cowlib ~> 2.8.0 or ~> 2.9.1 or 2.11.0.
    And because cowboy >= 2.10.0 and < 2.12.0 depends on cowlib 2.12.1, cowboy >= 2.7.0 and < 2.12.0 requires cowlib ~> 2.8.0 or ~> 2.9.1 or 2.11.0 or 2.12.1.
    And because cowboy >= 2.12.0 depends on cowlib 2.13.0, cowboy >= 2.7.0 requires cowlib ~> 2.8.0 or ~> 2.9.1 or 2.11.0 or 2.12.1 or 2.13.0.
    And because runlet requires cowlib ~> 2.6.0 or ~> 2.7.0 (1), runlet is incompatible with cowboy >= 2.7.0.
    And because every version of cowboy_telemetry depends on cowboy ~> 2.7, runlet is incompatible with cowboy_telemetry.
    And because plug_cowboy >= 2.4.0 depends on cowboy_telemetry ~> 0.3, runlet is incompatible with plug_cowboy >= 2.4.0.
    And because your app depends on plug_cowboy ~> 2.7, no version of runlet is allowed.
    So, because your app depends on runlet ~> 1.2.5, version solving failed.

**Comment by msantos** [comment]
Thanks @niranjanaryan for opening an issue! I've successfully tested adding runlet as a dep to the liveview demo.

If you run into any other problems or have any questions, please feel free to open an issue.

**Comment by niranjanaryan** [comment]
Thanks @msantos  , retry with new settings to try open new issues to explore deeper
